apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
spec:
  selector:
    matchLabels:
      app: webapp2
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
        - name: apicontagem
          image: renatogroffe/apicontagem-dotnet7-simulacaohealthcheck:2
          env:
          - name: MensagemVariavel
            value: Testes com Kubernetes Workload Scaler do KEDA
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp2-service
spec:
  selector:
    app: webapp2
  ports:
    - port: 80
  type: LoadBalancer